# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.9

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install poetry
  - poetry install -v
  - export PYTHONPATH="$PYTHONPATH:$(pwd)/src"
  - git config --global user.email ruthie@andrewlevan.com
  - git config --global user.name robo_ruthie
  - git config --global credential.helper cache

stages:
  - Static Analysis
  - Tests
  - Build
  - Publish

Pylint:
  stage: Static Analysis
  retry: 1
  script:
    - pylint -E -d C0301 src/horizons_client tests

Black:
  stage: Static Analysis
  retry: 1
  script:
    - python -m black . --check --verbose

Unit:
  stage: Tests
  retry: 1
  script:
    - pytest -v ./tests/unittests
#
#Functional:
#  stage: Tests
#  script:
#    - pytest -v ./tests/functional

Build and Publish Package:
  stage: Build
  retry: 1
#  only:
#    - main
  artifacts:
    untracked: true
    paths:
      - dist/
  script:
    - poetry build --format wheel
    - twine upload --repository-url http://pypi.home ./dist/*
